version: "3"
services:
  brain:
    image: moab/brain
    container_name: brain1
    stop_grace_period: 0s
    ports: [ 5000:5000 ]
  custom1:
    image: moab/brain
    container_name: custom1
    stop_grace_period: 0s
    ports: [ 5001:5000 ]
  custom2:
    image: moab/brain
    container_name: custom2
    stop_grace_period: 0s
    ports: [ 5002:5000 ]
