#!/bin/bash

# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

set -eo pipefail

println() { printf '%s\n' "$*"; }
die()     { ret=$?; printf "%s\n" "$@" >&2; exit "$ret"; }

# change directories to the folder hosting this script
readonly _D="$(dirname "$(readlink -f "$0")")" && cd "$_D"

usage() {
cat <<-HERE 
    Usage: $0 [tag=\$MOAB_TAG]

    Builds a Dockerfile called "moab/control:tag", where 
    tag is the first parameter. It defaults to 
    the environment variable MOAB_TAG. 

    Example:
        $0 3.0
        MOAB_TAG=3.0 $0

HERE
exit 3
}

TAG=${1:-${MOAB_TAG:-undefined}}
[[ $TAG = "undefined" ]] && usage

println "Making docker image: moab/control:$TAG"

# Python < 3.8 leaves __pycache__ folders *everywhere*.
# Since we run as sudo in dev-mode, they're not possible to delete in this non-sudo script.
# And we can't Docker RUN COPY . these files into the image with them there, so:
find . -name '__pycache__' -print > /dev/null || die "Run before building Dockerfile: sudo ./pyclean.sh"

export DOCKER_BUILDKIT=1
docker build -t moab/control:"$TAG" .
sha=$(docker images -q moab/control:"$TAG")
docker tag "$sha" moab/control:latest

