version: "3"
services:

  brain:
    image: moab/brain
    container_name: brain1
    stop_grace_period: 0s
    ports: [ 5000:5000 ]

  # custom1:
  #   image:  
  #   container_name: custom1
  #   stop_grace_period: 0s
  #   ports: [ 5000:5000 ]
  
  # custom2:
  #   image: 
  #   container_name: custom2
  #   stop_grace_period: 0s
  #   ports: [ 5000:5000 ]

# Add your trained Project Bonsai brains above.
#
#   image: the URL from your "docker pull" to azuercr.io
#   container_name: optional name that appears in the Moab screen
#   stop_grace_period: allows brains to shut down quickly
#   ports: first number must be between 5001 and 6000, and unique
#
# Spacing matters in YAML so the custom brain below should line up
# with the template show above.
#
# Example:

# custom1:
#   image: scotstan.azurecr.io/a988a049-1111-ffff-eeee-ee55999a9723/my_balance1_test:1-linux-arm32v7
#   container_name: balance1
#   stop_grace_period: 0s
#   ports: [ 5001:5000 ]
