#!/bin/bash
# vim:ft=sh ts=4 sw=4 et

# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# This script swaps Docker for Moby Engine


set -v
set -euo pipefail   # unofficial bash strict mode

require() { hash "$@" || exit 127; }
println() { printf '%s\n' "$*"; }
die()     { ret=$?; printf "%s\n" "$@" >&2; exit "$ret"; }

# Run as non-root check
[[ $EUID -ne 0 ]] || die "$0 run as pi user, not root"

## Log script output
exec 1> >(tee "/tmp/stdout.log")
exec 2> >(tee "/tmp/stderr.log")

## Set CWD to the location where this script is running
## $_D -> full path to folder where script is 
## $_P -> parent path (usually /home/pi/moab)
readonly _D="$(dirname "$(readlink -f "$0")")" && cd "$_D"
readonly _P=$(dirname $_D)

# Warn that this will remove all current brains

# Stop moab and related brain services
sudo systemctl stop menu brain docker iotedge || true

# Remove Docker's docker
sudo apt-get purge -y docker-ce 
sudo apt-get autoremove -y
sudo rm -rf /var/lib/docker /etc/docker

# Add Microsoft as APT source for moby-engine
curl https://packages.microsoft.com/config/debian/stretch/multiarch/prod.list > /tmp/microsoft.list
sudo cp /tmp/microsoft.list /etc/apt/sources.list.d
curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > /tmp/microsoft.gpg
sudo cp /tmp/microsoft.gpg /etc/apt/trusted.gpg.d

# Install docker "moby-engine"
sudo apt-get update --allow-releaseinfo-change -y || $TRUE
sudo apt-get install moby-engine -y

# Reload default brain
sudo systemctl start docker
wget https://github.com/microsoft/moabian/releases/download/v.2.4.0/brain.77b0.tar.gz -O /tmp/brain.tar.gz
docker load < /tmp/brain.tar.gz
docker tag 77b0 moab/brain:latest

# change branches
cd ~/moab
git checkout main
git pull
git checkout iot_telem_v2
bot reset

# restart Moab as-is
sudo systemctl start brain menu

# Azure IoT Edge version 1.1 (LTS)
sudo apt-get install -y libiothsm=1.1.1-1 iotedge=1.1.1-1

