#!/bin/bash
# vim:ft=sh ts=4 sw=4 et

#shopt -s nocasematch expand_aliases

brain_paths() {
    docker-compose config | grep "image:" | sed -r 's/.*image: (.+)/\1/'
}

brain_sha() {
    docker inspect "$1" | grep Id | sed -r 's/.*:([a-z0-9]*)",/\1/'
}

save_brains() {
    local p=$(brain_paths)

    mkdir --parents /tmp/brains

    for i in $p; do
        sha=$(brain_sha "$i")
        sha4=${sha:0:4}

        echo "docker save $sha4 > /tmp/brains/$sha4.tar.gz"
        docker save $sha4 > /tmp/brains/$sha4.tar.gz
    done
}

load_brains() {
    for i in /tmp/brains/*; do
        docker load < $i
    done
}

save_brains
#load_brains
