#!/bin/bash
# vim:ts=4 sw=4 et

# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

##
## Install the BCM2835 C library from source
##

set -euo pipefail   # unofficial bash strict mode

require() { hash "$@" || exit 127; }
println() { printf '%s\n' "$*"; }
die()     { ret=$?; printf "%s\n" "$@" >&2; exit "$ret"; }

# Only continue if we are running as sudo (for the make install)
[[ $EUID -eq 0 ]] || die "$0 needs to run as root. Try again with sudo."

# Test to see if library is already installed
echo 'int main(){}' | gcc -o /dev/null -x c - -lbcm2835 2>/dev/null && die "lib already installed"

# Create a temp folder to download and compile in to
T=$(mktemp -d --suffix=.moab)
trap 'rm -rf $T' EXIT
cd "$T"

ver="-1.64"
wget --no-verbose http://www.airspayce.com/mikem/bcm2835/bcm2835"$ver".tar.gz
tar xf bcm2835"$ver".tar.gz

cd bcm2835"$ver"
./configure > /dev/null
make > /dev/null
make install > /dev/null

exit 0
