#!/bin/bash

# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

set -euo pipefail   # unofficial bash strict mode
trap 's=$?; echo "$0: Error on line "$LINENO": $BASH_COMMAND"; exit $s' ERR

require() { hash "$@" || exit 127; }
println() { printf '%s\n' "$*"; }
die()     { ret=$?; printf "%s\n" "$@" >&2; exit "$ret"; }

FW_FILENAME=${1:-"firmware.bin"}

[[ $EUID -eq 0 ]] || die "$0 needs to run as root. Try again with sudo."

require wget
require mcumgr

readonly _D="$(dirname "$(readlink -f "$0")")" && cd "$_D"

function warn {
    local color=$(tput smso)$(tput setaf 1)             # inverse, red
    local reset=$(tput sgr0)
    printf '%s\n' "${color}$1${reset}" >&2
}

function info {
    local color=$(tput smso)$(tput setaf 2)             # inverse, green
    local reset=$(tput sgr0)
    printf '%s\n' "${color}$1${reset}"
}

# bcm2835
if [[ ! -e /usr/local/lib/libbcm2835.a ]]; then
    warn "Install the bcm2835 library first from ~/moab/sw/bin/bcm2835"
    exit 127
fi

info "making flash program"
make

info "flash $FW_FILENAME"
./flash "$FW_FILENAME"

# cleanup
make clean

info "finished"
